### ISSUE TITLE
How to install on fedora?

### ISSUE THREAD

**Issue by inzar98** [michelesr/nvidia-xrun-pm#3]
There is any repo avaible for fedora? I want keep it updated by it :/

**Comment by michelesr** [comment]
Hi @inzar98. I don't plan to support official repositories for specific Linux distributions, even though I created a [package](https://aur.archlinux.org/packages/nvidia-xrun-pm/) for the Arch User Repository. The original nvidia-xrun seems to have a repository for Fedora/CentOS/RHEL (at least according to [this](https://github.com/Witko/nvidia-xrun#copr-repo-for-fedora-27)) but I don't know anything about it. There's a [RPM spec](https://github.com/michelesr/nvidia-xrun-pm/blob/master/rpm-spec/nvidia-xrun.spec) in the source tree of nvidia-xrun-pm, but it might need to be updated. I'll have a look when I have some free time, meanwhile feel free to update it and open a PR. 

Bear in mind that #2 introduced a new [configuration file](https://github.com/michelesr/nvidia-xrun-pm/blob/master/config/nvidia-xrun) that has to be installed in `/etc/default/nvidia-xrun`.

@ekultails: is it something that you could look at?

**Comment by LukeShortCloud** [comment]
Hey everyone, yes, I can update the RPM spec to include the new configuration file and also create a Fedora COPR repository for nvidia-xrun-pm. I will post back once I have updates on the matter.

**Comment by michelesr** [comment]
@ekultails great! 

Do you think it could be a good idea to use the release tag instead of master branch? That's what I'm doing in AUR at the moment: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nvidia-xrun-pm

**Comment by LukeShortCloud** [comment]
I agree, that would be a more preferable approach to pull specified releases from GitHub. I will be sure to update RPM spec file for that as well.

**Comment by michelesr** [comment]
@ekultails is there any reason to keep the spec in the codebase? If you're gonna push the repository to COPR it might make sense to just remove it from the repository and put a link in the readme instead?

**Comment by LukeShortCloud** [comment]
Unlike the AUR, the Fedora COPR does not provide a built-in means to git revision the history of the RPM spec file. It will build a source RPM package that can be downloaded and then extracted to get the spec file. The downside is that it is harder to maintain that spec file and we are no longer keeping track of the revision history of it.

As an alternative, I could create a new/separate GitHub repository to only host the RPM spec file and then we can link that in the readme file of the nvidia-xrun-pm repository.

**Comment by michelesr** [comment]
In that case let's keep it here for now, I don't wanna diverge too much from upstream, and TBH I hope nvidia-xrun-pm code can be merged in the upstream code in the future... if the merge won't happen in a considerable period of time I'd be glad to move the spec out of the repo as I don't feel confident enough to maintain it.

**Comment by LukeShortCloud** [comment]
Right, I completely understand. For now, it appears as if the maintainer of nvidia-xrun is missing/busy. :-/

**Comment by michelesr** [comment]
@ekultails are you still ok to do this? I haven't received any update from you.

**Comment by LukeShortCloud** [comment]
@michelesr My apologies, I have been traveling a lot lately. I still plan on taking care of this when I get some more free time.

**Comment by LukeShortCloud** [comment]
@michelesr I have updated the RPM, tested it out on my local workstation, and got RPMs built for Fedora, RHEL, and openSUSE distributions.

@inzar98 Can you try installing the RPM from the Fedora COPR now? Let us know how it goes. https://copr.fedorainfracloud.org/coprs/ekultails/nvidia-xrun-pm/

**Comment by michelesr** [comment]
Fixed by #4
